package com.eas.ui.admin;
import com.eas.config.Database; import com.eas.model.UserSession; import com.eas.service.AuditService; import com.eas.util.*; import java.awt.*; import java.sql.*; import javax.swing.*;
public class AccountManagementPanel extends ReadOnlyQueryPanel { private final UserSession session; private final JTextField user=new JTextField(12),name=new JTextField(18),email=new JTextField(19),phone=new JTextField(12); private final JPasswordField pass=new JPasswordField(12); private final JComboBox<String> role=new JComboBox<String>(new String[]{"EMPLOYEE","ADMIN"});
 public AccountManagementPanel(UserSession s){super("User and Administrator Accounts","SELECT id,username,role,full_name,email,phone,status,created_at FROM users ORDER BY id DESC","SELECT id,username,role,full_name,email,phone,status,created_at FROM users WHERE username LIKE ? OR full_name LIKE ? OR email LIKE ? ORDER BY id DESC","accounts");session=s;JPanel f=new JPanel();f.setBorder(BorderFactory.createTitledBorder("Create Account / Selected Account Actions"));f.add(new JLabel("Username"));f.add(user);f.add(new JLabel("Password"));f.add(pass);f.add(new JLabel("Name"));f.add(name);f.add(new JLabel("Email"));f.add(email);f.add(new JLabel("Phone"));f.add(phone);f.add(role);JButton add=UITheme.button("CREATE");JButton reset=UITheme.button("RESET PASSWORD");JButton toggle=UITheme.button("TOGGLE STATUS");f.add(add);f.add(reset);f.add(toggle);add(f,BorderLayout.SOUTH);add.addActionListener(e->create());reset.addActionListener(e->reset());toggle.addActionListener(e->toggle());}
 private Integer selected(){int row=table.getSelectedRow();return row<0?null:Integer.valueOf(table.getValueAt(row,0).toString());}
 private void create(){try(Connection c=Database.getConnection();PreparedStatement p=c.prepareStatement("INSERT INTO users(username,password_hash,role,full_name,email,phone,status) VALUES(?,?,?,?,?,?,'ACTIVE')")){p.setString(1,user.getText().trim());p.setString(2,PasswordUtil.hash(new String(pass.getPassword())));p.setString(3,role.getSelectedItem().toString());p.setString(4,name.getText().trim());p.setString(5,email.getText().trim());p.setString(6,phone.getText().trim());p.executeUpdate();AuditService.log(session.getId(),"CREATE","ACCOUNTS","Created account "+user.getText());load("");Dialogs.info(this,"Account created. For employee role, complete the employee record and link its User ID.");}catch(Exception ex){Dialogs.error(this,ex.getMessage());}}
 private void reset(){Integer id=selected();if(id==null){Dialogs.error(this,"Select an account.");return;}String np=JOptionPane.showInputDialog(this,"Enter new password (minimum 6 characters):");if(np==null||np.length()<6){Dialogs.error(this,"Password not changed.");return;}try(Connection c=Database.getConnection();PreparedStatement p=c.prepareStatement("UPDATE users SET password_hash=? WHERE id=?")){p.setString(1,PasswordUtil.hash(np));p.setInt(2,id);p.executeUpdate();AuditService.log(session.getId(),"RESET_PASSWORD","ACCOUNTS","Reset user password.");Dialogs.info(this,"Password reset.");}catch(Exception ex){Dialogs.error(this,ex.getMessage());}}
 private void toggle(){Integer id=selected();if(id==null){Dialogs.error(this,"Select an account.");return;}if(id==session.getId()){Dialogs.error(this,"You cannot deactivate your own current account.");return;}try(Connection c=Database.getConnection();PreparedStatement p=c.prepareStatement("UPDATE users SET status=IF(status='ACTIVE','INACTIVE','ACTIVE') WHERE id=?")){p.setInt(1,id);p.executeUpdate();load("");AuditService.log(session.getId(),"STATUS","ACCOUNTS","Toggled account status.");}catch(Exception ex){Dialogs.error(this,ex.getMessage());}}
}
