package com.eas.ui.admin;
import com.eas.config.Database; import com.eas.model.UserSession; import com.eas.service.AuditService; import com.eas.util.*; import java.awt.*; import java.sql.*; import java.util.*; import javax.swing.*;
public class GenericCrudPanel extends ReadOnlyQueryPanel { private final UserSession session; private final String module,insertSql,updateSql,deleteSql; private final LinkedHashMap<String,JTextField> fields=new LinkedHashMap<String,JTextField>(); private final JTextField id=new JTextField(7);
 public GenericCrudPanel(UserSession s,String title,String module,String base,String search,String export,String insert,String update,String delete,String...labels){super(title,base,search,export);session=s;this.module=module;insertSql=insert;updateSql=update;deleteSql=delete;id.setEditable(false);JPanel f=new JPanel(new GridBagLayout());f.setBorder(BorderFactory.createTitledBorder("Record Entry / Edit"));GridBagConstraints g=new GridBagConstraints();g.insets=new Insets(3,4,3,4);g.fill=GridBagConstraints.HORIZONTAL;int x=0;add(f,g,x++,"ID",id);for(String label:labels){JTextField t=new JTextField(10);fields.put(label,t);add(f,g,x++,label,t);}JPanel buttons=new JPanel();JButton create=UITheme.button("ADD");JButton edit=UITheme.button("UPDATE");JButton remove=UITheme.button("DELETE");JButton clear=UITheme.button("CLEAR");buttons.add(create);buttons.add(edit);buttons.add(remove);buttons.add(clear);g.gridx=0;g.gridy=2;g.gridwidth=Math.max(2,x);f.add(buttons,g);add(f,BorderLayout.SOUTH);table.getSelectionModel().addListSelectionListener(e->{if(!e.getValueIsAdjusting())select();});create.addActionListener(e->insert());edit.addActionListener(e->update());remove.addActionListener(e->delete());clear.addActionListener(e->clear());}
 private void add(JPanel p,GridBagConstraints g,int x,String label,JTextField t){g.gridx=x;g.gridy=0;p.add(new JLabel(label),g);g.gridy=1;p.add(t,g);} private void select(){int r=table.getSelectedRow();if(r<0)return;r=table.convertRowIndexToModel(r);id.setText(String.valueOf(table.getModel().getValueAt(r,0)));int c=1;for(JTextField t:fields.values()){t.setText(c<table.getColumnCount()&&table.getModel().getValueAt(r,c)!=null?table.getModel().getValueAt(r,c).toString():"");c++;}}
 private void params(PreparedStatement p)throws SQLException{int i=1;for(JTextField t:fields.values()){String v=t.getText().trim();if(v.isEmpty())p.setNull(i++,Types.VARCHAR);else p.setString(i++,v);}}
 private void insert(){try(Connection c=Database.getConnection();PreparedStatement p=c.prepareStatement(insertSql)){params(p);p.executeUpdate();AuditService.log(session.getId(),"CREATE",module,"Added record.");clear();load("");Dialogs.info(this,"Record added.");}catch(Exception ex){Dialogs.error(this,ex.getMessage());}}
 private void update(){if(id.getText().isEmpty()){Dialogs.error(this,"Select a record first.");return;}try(Connection c=Database.getConnection();PreparedStatement p=c.prepareStatement(updateSql)){params(p);p.setInt(fields.size()+1,Integer.parseInt(id.getText()));p.executeUpdate();AuditService.log(session.getId(),"UPDATE",module,"Updated record #"+id.getText());clear();load("");Dialogs.info(this,"Record updated.");}catch(Exception ex){Dialogs.error(this,ex.getMessage());}}
 private void delete(){if(id.getText().isEmpty()||!Dialogs.confirm(this,"Delete selected record?"))return;try(Connection c=Database.getConnection();PreparedStatement p=c.prepareStatement(deleteSql)){p.setInt(1,Integer.parseInt(id.getText()));p.executeUpdate();AuditService.log(session.getId(),"DELETE",module,"Deleted record #"+id.getText());clear();load("");}catch(Exception ex){Dialogs.error(this,ex.getMessage());}}
 private void clear(){id.setText("");for(JTextField t:fields.values())t.setText("");table.clearSelection();}
}
